export const userConstants = {
    LOGIN_OPEN: "LOGIN_OPEN",
    LOGIN_CLOSE: "LOGIN_CLOSE",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS"
};

export const notificationConstants = {
    NOTIFICATION_OPEN: "NOTIFICATION_OPEN",
    NOTIFICATION_CLOSE: "NOTIFICATION_CLOSE"
};
