export const authoritiesConstants = {
    ROLE_ADMIN: "ROLE_ADMIN",
    ROLE_TUTOR: "ROLE_TUTOR",
    ROLE_STUDENT: "ROLE_STUDENT"
};

export const menuConstants = {
    LOGIN_OPEN: "LOGIN_OPEN",
    LOGIN_CLOSE: "LOGIN_CLOSE",
    LOGIN_ERROR: "LOGIN_ERROR"
};

export const authConstants = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS"
};

export const notificationConstants = {
    NOTIFICATION_OPEN: "NOTIFICATION_OPEN",
    NOTIFICATION_CLOSE: "NOTIFICATION_CLOSE"
};

export const dataTableConstants = {
    LOAD_BEGIN: "LOAD_BEGIN",
    LOAD_END: "LOAD_END",
    LOAD_DATA_SUCCESS: "LOAD_DATA_SUCCESS",
    LOAD_DATA_ERROR: "LOAD_DATA_ERROR",
    CHANGE_PAGE: "CHANGE_PAGE",
    CHANGE_PAGE_SIZE: "CHANGE_PAGE_SIZE",
    CHANGE_PAGE_SORTING: "CHANGE_PAGE_SORTING"
};
